import { useState } from 'react';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { DraggablePatch } from './components/DraggablePatch';
import { JeansCanvas } from './components/JeansCanvas';
import { SuccessModal } from './components/SuccessModal';
import { supabase } from '../lib/supabaseClient';

// ============================================================
// Phase 4: Local patch assets from /public/patches/
// ============================================================
const AVAILABLE_PATCHES = [
  { id: 'patch-1', name: 'Flower',    price: 8.50,  imageUrl: '/patches/flower.png' },
  { id: 'patch-2', name: 'Star',      price: 6.00,  imageUrl: '/patches/star.png' },
  { id: 'patch-3', name: 'Peace',     price: 7.50,  imageUrl: '/patches/peace.png' },
  { id: 'patch-4', name: 'Moon',      price: 9.00,  imageUrl: '/patches/moon.png' },
  { id: 'patch-5', name: 'Heart',     price: 5.50,  imageUrl: '/patches/heart.png' },
  { id: 'patch-6', name: 'Butterfly', price: 10.00, imageUrl: '/patches/butterfly.png' },
];

const BASE_JEANS_PRICE = 45.00;

// ============================================================
// Phase 1: PlacedPatch now uses percentage coordinates
// ============================================================
interface PlacedPatch {
  id: string;
  patchId: string;
  name: string;
  price: number;
  imageUrl: string;
  /** Percentage (0–100) relative to canvas width */
  x: number;
  /** Percentage (0–100) relative to canvas height */
  y: number;
}

export default function App() {
  const [placedPatches, setPlacedPatches] = useState<PlacedPatch[]>([]);
  const [showModal, setShowModal]         = useState(false);
  const [designId, setDesignId]           = useState('');
  const [isSubmitting, setIsSubmitting]   = useState(false);
  const [error, setError]                 = useState<string | null>(null);
  const [baseSize, setBaseSize]           = useState<'S' | 'M' | 'L'>('M');

  const totalPrice = BASE_JEANS_PRICE + placedPatches.reduce((sum, p) => sum + p.price, 0);

  const handlePatchAdded = (patch: PlacedPatch) => {
    setPlacedPatches((prev) => [...prev, patch]);
  };

  const handleRemovePatch = (id: string) => {
    setPlacedPatches((prev) => prev.filter((p) => p.id !== id));
  };

  // ============================================================
  // Phase 3: Real Supabase insert replacing the mock ID generator
  // ============================================================
  const handleFinalizeDesign = async () => {
    if (placedPatches.length === 0) return;

    setError(null);
    setIsSubmitting(true);
    setDesignId('');   // clears previous ID; modal shows spinner while empty
    setShowModal(true);

    try {
      // Step 1: Insert the design record — DB trigger generates design_id
      const { data: designRow, error: designError } = await supabase
        .from('designs')
        .insert({
          base_size:   baseSize,
          total_price: totalPrice,
          // design_id is auto-generated by the DB trigger
        })
        .select('id, design_id')
        .single();

      if (designError) throw designError;

      const dbDesignId  = designRow.id;
      const humanId     = designRow.design_id;

      // Step 2: Insert all placed patches linked to the design
      const patchRows = placedPatches.map((p) => ({
        design_id:       dbDesignId,
        patch_id:        p.patchId,
        coord_x_percent: p.x,
        coord_y_percent: p.y,
      }));

      const { error: patchError } = await supabase
        .from('design_patches')
        .insert(patchRows);

      if (patchError) throw patchError;

      // Step 3: Show the real design ID in the modal
      setDesignId(humanId);

    } catch (err: unknown) {
      console.error('[Supabase] Failed to save design:', err);
      setShowModal(false);

      // Graceful fallback: generate a local ID so the user can still checkout
      const fallbackId = `PATCH-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
      setDesignId(fallbackId);
      setShowModal(true);

      setError('Could not save to database. A local ID was generated — please note it for reference.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCloseModal = () => {
    if (isSubmitting) return; // prevent close while saving
    setShowModal(false);
  };

  return (
    <DndProvider backend={HTML5Backend}>
      <div className="min-h-screen" style={{ backgroundColor: '#FEFCFA' }}>

        {/* ── Navigation Bar ── */}
        <nav
          className="px-8 py-5 flex items-center justify-between border-b"
          style={{ borderColor: '#E8E4DF' }}
        >
          <div className="flex items-center gap-3">
            <div
              className="w-9 h-9 rounded-full flex items-center justify-center"
              style={{ backgroundColor: '#A8B5A0' }}
            >
              <span className="text-white text-sm font-bold">RJ</span>
            </div>
            <span className="text-xl font-semibold text-stone-800 tracking-tight">ReThreaded</span>
          </div>

          {/* Size selector */}
          <div className="flex items-center gap-3">
            <span className="text-sm text-stone-500">Base size:</span>
            {(['S', 'M', 'L'] as const).map((size) => (
              <button
                key={size}
                id={`size-btn-${size}`}
                onClick={() => setBaseSize(size)}
                className="w-9 h-9 rounded-full text-sm font-medium border transition-all"
                style={{
                  borderColor:     baseSize === size ? '#A8B5A0' : '#E8E4DF',
                  backgroundColor: baseSize === size ? '#A8B5A0' : 'transparent',
                  color:           baseSize === size ? 'white'   : '#78716C',
                }}
                aria-pressed={baseSize === size}
                aria-label={`Select size ${size}`}
              >
                {size}
              </button>
            ))}
          </div>

          {/* Price pill */}
          <div
            className="px-6 py-2 rounded-full"
            style={{ backgroundColor: '#F5F1ED' }}
          >
            <span className="text-stone-500 text-sm">Total: </span>
            <span className="text-stone-800 font-semibold">RM {totalPrice.toFixed(2)}</span>
          </div>
        </nav>

        {/* ── Main Content ── */}
        <div className="flex h-[calc(100vh-73px)]">

          {/* Left Panel — Canvas */}
          <div className="w-[60%] p-8">
            <JeansCanvas
              onPatchAdded={handlePatchAdded}
              placedPatches={placedPatches}
              onRemovePatch={handleRemovePatch}
            />
          </div>

          {/* Right Panel — Patch Inventory */}
          <div
            className="w-[40%] p-8 flex flex-col border-l"
            style={{ backgroundColor: '#F5F1ED', borderColor: '#E8E4DF' }}
          >
            <h2 className="text-xl font-semibold mb-1 text-stone-800">Select Your Patches</h2>
            <p className="text-sm text-stone-500 mb-6">Drag a patch onto the jeans to place it</p>

            {/* Patch grid */}
            <div className="flex-1 overflow-y-auto pr-1">
              <div className="grid grid-cols-2 gap-4">
                {AVAILABLE_PATCHES.map((patch) => (
                  <DraggablePatch
                    key={patch.id}
                    id={patch.id}
                    name={patch.name}
                    price={patch.price}
                    imageUrl={patch.imageUrl}
                  />
                ))}
              </div>
            </div>

            {/* Action bar */}
            <div className="mt-6 pt-6 border-t" style={{ borderColor: '#D6D0CB' }}>

              {/* Error banner */}
              {error && (
                <div
                  className="mb-4 px-4 py-3 rounded-lg text-sm text-amber-800 border border-amber-300"
                  style={{ backgroundColor: '#FEF3C7' }}
                  role="alert"
                >
                  ⚠️ {error}
                </div>
              )}

              {/* Summary */}
              {placedPatches.length > 0 && (
                <div className="mb-4 space-y-1">
                  {placedPatches.map((p) => (
                    <div key={p.id} className="flex justify-between text-xs text-stone-500">
                      <span>{p.name}</span>
                      <span>+RM {p.price.toFixed(2)}</span>
                    </div>
                  ))}
                  <div className="flex justify-between text-xs text-stone-500 pt-1 border-t" style={{ borderColor: '#D6D0CB' }}>
                    <span>Base jeans ({baseSize})</span>
                    <span>RM {BASE_JEANS_PRICE.toFixed(2)}</span>
                  </div>
                </div>
              )}

              <button
                id="finalize-design-btn"
                onClick={handleFinalizeDesign}
                disabled={placedPatches.length === 0 || isSubmitting}
                className="w-full py-4 px-6 rounded-xl text-white font-medium transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                style={{
                  backgroundColor: '#A8B5A0',
                  boxShadow: placedPatches.length > 0
                    ? '0 4px 12px rgba(168, 181, 160, 0.35)'
                    : 'none',
                }}
              >
                {isSubmitting ? 'Saving Design…' : 'Finalize Design'}
              </button>

              {placedPatches.length === 0 && (
                <p className="text-xs text-center mt-3 text-stone-400">
                  Add at least one patch to continue
                </p>
              )}
            </div>
          </div>
        </div>

        {/* ── Success Modal ── */}
        <SuccessModal
          isOpen={showModal}
          onClose={handleCloseModal}
          designId={designId}
        />
      </div>
    </DndProvider>
  );
}